name: Rust CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install playerctl
      run: sudo apt-get update && sudo apt-get install -y playerctl

    - name: Build
      run: cargo build --verbose

    - name: Run example
      run: cargo run --example basic
